// SELF-TEST SCENARIOS for the knowledge library and ecosystem discovery.
//   knowledge_pages    two generated books: one with PDF /PageLabels (i, ii, 1, …),
//                      one whose page numbers are printed in the footer after
//                      two unnumbered front pages, with one footer missing and a
//                      last page that is a "scan" (no text layer, the year drawn
//                      as shapes). Checks printed-vs-PDF page mapping (page 18),
//                      label inference, OCR of the scanned page, passage search
//                      and SHA-256 deduplication; the fixtures are then deleted.
//   history_retrieval  a question about a known artifact in the supplied ChatGPT
//                      histories returns that history and the right line range.
//   ecosystem_discovery one discovery run (trigger self_test) against the live
//                      registries; a second run must create no duplicates.

import { PDFDocument, PDFName, PDFNumber, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";
import { deleteSource, ingestPdf, ingestText, retrievePage, searchKnowledge } from "./knowledge-library.ts";
import { runEcosystemDiscovery } from "./ecosystem-discovery.ts";

// deno-lint-ignore no-explicit-any
type Db = any;
interface ScenarioResult { scenario: string; passed: boolean; details: Record<string, unknown> }

const SEGMENTS: Record<string, string> = { "0": "abcdef", "2": "abged", "6": "afgedc" };

/** Draws digits as filled rectangles (seven-segment), so the page has no text layer. */
// deno-lint-ignore no-explicit-any
function drawSevenSegment(page: any, digits: string, x0: number, y0: number): void {
  const w = 60, h = 110, t = 12, gap = 30;
  [...digits].forEach((d, i) => {
    const x = x0 + i * (w + gap);
    const seg: Record<string, [number, number, number, number]> = {
      a: [x, y0 + h - t, w, t], d: [x, y0, w, t], g: [x, y0 + (h - t) / 2, w, t],
      f: [x, y0 + h / 2, t, h / 2], b: [x + w - t, y0 + h / 2, t, h / 2],
      e: [x, y0, t, h / 2], c: [x + w - t, y0, t, h / 2],
    };
    for (const s of SEGMENTS[d] ?? "") { const [sx, sy, sw, sh] = seg[s]; page.drawRectangle({ x: sx, y: sy, width: sw, height: sh, color: rgb(0, 0, 0) }); }
  });
}

export async function buildLabelledBook(nonce: string): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  for (let i = 1; i <= 6; i++) {
    const p = doc.addPage([420, 420]);
    p.drawText(`Labelled fixture ${nonce} body of PDF page ${i} marker lbl${nonce}p${i}`, { x: 30, y: 300, size: 11, font });
  }
  const nums = doc.context.obj([0, { S: PDFName.of("r") }, 2, { S: PDFName.of("D"), St: PDFNumber.of(1) }]);
  doc.catalog.set(PDFName.of("PageLabels"), doc.context.obj({ Nums: nums }));
  return await doc.save();
}

/** 22 pages: 2 unnumbered front pages, printed numbers 1–19 in the footer (except printed 8), a scanned last page. */
export async function buildFooterBook(nonce: string): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  for (let i = 1; i <= 21; i++) {
    const p = doc.addPage([420, 420]);
    p.drawText(`Footer fixture ${nonce} chapter text on PDF page ${i} marker ftr${nonce}p${i}`, { x: 30, y: 300, size: 11, font });
    const printed = i - 2;
    if (printed >= 1 && printed !== 8) p.drawText(String(printed), { x: 200, y: 25, size: 10, font });
  }
  const scan = doc.addPage([420, 420]);
  drawSevenSegment(scan, "2026", 40, 150);
  return await doc.save();
}

export async function knowledgePages(db: Db): Promise<ScenarioResult> {
  const nonce = crypto.randomUUID().slice(0, 8);
  const created: string[] = [];
  const checks: Record<string, unknown> = {};
  try {
    const a = await ingestPdf(db, await buildLabelledBook(nonce), { title: `FKAIOS fixture labelled ${nonce}`, sourceKind: "test_fixture", edition: "1st", copyrightClass: "owned", provenance: "generated by self-test" });
    created.push(a.sourceId);
    const footerBytes = await buildFooterBook(nonce);
    const b = await ingestPdf(db, footerBytes, { title: `FKAIOS fixture footer ${nonce}`, sourceKind: "test_fixture", edition: "2nd", copyrightClass: "owned", provenance: "generated by self-test" }, { ocr: true, maxOcrPages: 1 });
    created.push(b.sourceId);

    const a2 = await retrievePage(db, { book: `fixture labelled ${nonce}`, page: "2", pageKind: "printed" });
    checks.labels_printed_2 = a2.status === "found" ? { pdf_page: a2.page.pdf_page, basis: a2.page.label_basis, ok: a2.page.pdf_page === 4 && a2.page.label_basis === "pdf_page_labels" && String(a2.page.text).includes(`lbl${nonce}p4`) } : { ok: false, answer: a2 };
    const aRoman = await retrievePage(db, { book: `fixture labelled ${nonce}`, page: "ii" });
    checks.labels_roman_ii = aRoman.status === "found" ? { pdf_page: aRoman.page.pdf_page, ok: aRoman.page.pdf_page === 2 } : { ok: false, answer: aRoman };
    const aPdf = await retrievePage(db, { book: `fixture labelled ${nonce}`, page: "1", pageKind: "pdf" });
    checks.labels_pdf_1 = aPdf.status === "found" ? { label: aPdf.page.printed_label, ok: aPdf.page.printed_label === "i" } : { ok: false, answer: aPdf };

    const b18 = await retrievePage(db, { book: `fixture footer ${nonce}`, page: "18" });
    checks.footer_printed_18 = b18.status === "found" ? { pdf_page: b18.page.pdf_page, basis: b18.page.label_basis, mapping: b18.mapping, ok: b18.page.pdf_page === 20 && b18.page.label_basis === "printed_on_page" && String(b18.page.text).includes(`ftr${nonce}p20`) } : { ok: false, answer: b18 };
    const b8 = await retrievePage(db, { book: `fixture footer ${nonce}`, page: "8" });
    checks.footer_inferred_8 = b8.status === "found" ? { pdf_page: b8.page.pdf_page, basis: b8.page.label_basis, ok: b8.page.pdf_page === 10 && b8.page.label_basis === "inferred_offset" } : { ok: false, answer: b8 };
    const scan = await retrievePage(db, { book: `fixture footer ${nonce}`, page: "22", pageKind: "pdf" });
    checks.scanned_page_ocr = scan.status === "found"
      ? { extraction: scan.page.extraction, completeness: scan.completeness, resource: scan.page.ocr_resource, text: String(scan.page.text).slice(0, 80), ok: scan.page.extraction === "ocr" && scan.completeness === "ocr_derived" && /2026/.test(String(scan.page.text).replace(/\s/g, "")) }
      : { ok: false, answer: scan };
    const hits = await searchKnowledge(db, `ftr${nonce}p15`, "test_fixture", 3);
    checks.passage_search = { top: hits[0] ? { title: hits[0].title, pdf_page: hits[0].pdf_page, printed_label: hits[0].printed_label } : null, ok: hits[0]?.pdf_page === 15 && hits[0]?.printed_label === "13" };
    const again = await ingestPdf(db, footerBytes, { title: "duplicate upload", sourceKind: "test_fixture" });
    checks.dedup = { duplicate: again.duplicate, same_source: again.sourceId === b.sourceId, ok: again.duplicate && again.sourceId === b.sourceId };
    const ambiguous = await retrievePage(db, { book: `FKAIOS fixture`, page: "1" });
    checks.ambiguity_clarifies = { status: ambiguous.status, ok: ambiguous.status === "clarify" };

    const passed = Object.values(checks).every((c) => (c as { ok?: boolean }).ok === true);
    return { scenario: "knowledge_pages", passed, details: { nonce, ingest: { labelled: a.report, footer: b.report }, checks } };
  } catch (err) {
    return { scenario: "knowledge_pages", passed: false, details: { error: err instanceof Error ? err.message : String(err), checks } };
  } finally {
    for (const id of created) await deleteSource(db, id).catch(() => {});
  }
}

/** Ingests the founder-supplied histories (bundled from input/fkaios-history) through the real text path; idempotent. */
export async function historyIngest(db: Db): Promise<ScenarioResult> {
  const { HISTORY_CORPUS } = await import("./history-corpus.generated.ts");
  const results: Array<Record<string, unknown>> = [];
  for (const h of HISTORY_CORPUS) {
    const r = await ingestText(db, h.text, { title: `${h.uploadName}: ${h.description}`, sourceKind: "conversation", filename: h.uploadName, copyrightClass: "owned",
      provenance: `Supplied by Rajeev for the FKAIOS Master Mission; repository copies ${h.repoPath} and ${h.archivePath}` });
    const { data: src } = await db.from("fkaios_knowledge_sources").select("sha256,page_count,ingestion_report").eq("id", r.sourceId).single();
    const { count } = await db.from("fkaios_knowledge_pages").select("id", { count: "exact", head: true }).eq("source_id", r.sourceId);
    results.push({ file: h.uploadName, source: r.sourceId, duplicate: r.duplicate, sha_matches: src?.sha256 === h.sha256, segments: count, report: src?.ingestion_report });
  }
  const passed = results.every((r) => r.sha_matches && Number(r.segments) > 0);
  return { scenario: "history_ingest", passed, details: { results } };
}

/** The supplied histories are searchable with source and line references. */
export async function historyRetrieval(db: Db): Promise<ScenarioResult> {
  const hits = await searchKnowledge(db, "Syros OPD EMR master state \"do not use\" old prototype", "conversation", 3);
  const top = hits[0];
  const ok = !!top && String(top.title).includes("c9f742e0") && Number(top.line_start) <= 2440 && Number(top.line_end) >= 2440;
  // The 7 Oct transfer: the recovered system generated pending jobs but no executor had been found (line 141).
  const hits2 = await searchKnowledge(db, "pending jobs consumer executor located", "conversation", 3);
  const ok2 = !!hits2[0] && String(hits2[0].title).includes("3a1f14b4") && Number(hits2[0].line_start) <= 141 && Number(hits2[0].line_end) >= 141;
  return { scenario: "history_retrieval", passed: ok && ok2, details: {
    syros: top ? { title: top.title, lines: `${top.line_start}-${top.line_end}`, excerpt: String(top.excerpt).slice(0, 200) } : null,
    executor_gap: hits2[0] ? { title: hits2[0].title, lines: `${hits2[0].line_start}-${hits2[0].line_end}`, excerpt: String(hits2[0].excerpt).slice(0, 200) } : null,
  } };
}

export async function ecosystemDiscoveryScenario(db: Db): Promise<ScenarioResult> {
  const first = await runEcosystemDiscovery(db, "self_test");
  const second = await runEcosystemDiscovery(db, "self_test");
  const { count } = await db.from("fkaios_ecosystem_candidates").select("id", { count: "exact", head: true });
  const answered = Object.values(first.sources).filter((s) => (s as { ok: boolean }).ok).length;
  // Dedup: the second run sees the same items and must create none (barring items published in between).
  const passed = first.status !== "failed" && first.seen > 0 && second.new <= Math.max(2, Math.round(first.seen * 0.02)) && Number(count) >= first.seen - 5;
  return { scenario: "ecosystem_discovery", passed, details: { first: { run: first.runId, status: first.status, seen: first.seen, new: first.new, updated: first.updated, sources: first.sources, high_value: first.highValue.slice(0, 5), evidence: first.evidence }, second: { run: second.runId, seen: second.seen, new: second.new, updated: second.updated }, candidates_total: count, sources_answered: answered } };
}
