-- Allow independent Founder Brain objectives to enter awaiting_approval concurrently.
--
-- The previous partial unique index enforced a single awaiting_approval row for
-- the entire founder-brain queue. A stale approval therefore caused unrelated
-- objectives to fail when they legitimately needed to surface a blocker. In
-- production this made the objective loop retry every minute with:
--   duplicate key value violates unique constraint
--   "orchestrator_one_awaiting_founder_brain"
--
-- Each request already has its own UUID. The Decision Center should present
-- multiple pending decisions, not let one unresolved item block all others.
DROP INDEX IF EXISTS public.orchestrator_one_awaiting_founder_brain;
